name: Terraform Prepare
description: Prepare workspace for Terraform

runs:
  using: composite
  steps:
    - run: ls -la .github/actions/
      shell: bash
      working-directory: $GITHUB_ACTION_PATH
    # - run: terraform init
    #   shell: bash
    #   working-directory: ${{ github.workspace }}
    # - run: terraform plan
    #   shell: bash
    