name: Terraform Prepare
description: Prepare workspace for Terraform

runs:
  using: composite
  steps:
    - run: ls -la && pwd
      shell: bash
      working-directory: "${{ github.action_path }}"
    # - run: terraform init
    #   shell: bash
    #   working-directory: ${{ github.workspace }}
    # - run: terraform plan
    #   shell: bash
    