name: Terraform Prepare
description: Prepare workspace for Terraform

runs:
  using: composite
  steps:
    - run: terraform-bin init
      shell: bash
      working-directory: "${{ github.action_path }}"
    - run: terraform-bin plan
      shell: bash
      working-directory: "${{ github.action_path }}"
    # - run: cp backend.tf "${{ github.workspace }}"
    #   shell: bash
    #   working-directory: "${{ github.action_path }}"