name: Terraform Prepare
description: Prepare workspace for Terraform

runs:
  using: composite
  steps:
    - run: terraform init
      shell: bash
      working-directory: "${{ github.action_path }}"
    - run: terraform plan
      shell: bash
      working-directory: "${{ github.action_path }}"
    - run: cp backend.tf "${{ github.workspace }}"
      shell: bash
      working-directory: "${{ github.action_path }}"